### PR TITLE
Update donut chart per recent changes

### LINKED ISSUE #19: Donut widget needs reworking
The PF4 donut chart appears to have changed again and needs a rework. The test for it has been marked with "skip" for now in #11

### PR DESCRIPTION
**Pull request by abalakh**
Fixes #19 

Few notes:

1. Most locators look worse, as class names were removed. I've filled https://github.com/patternfly/patternfly-react/issues/1932 to return class names, so hopefully at some point we'll be able to revert locators.
2. ~~Now we have a separate url for charts - `http://patternfly-react.surge.sh/patternfly-4/charts/*chart_name*` (same for demos, inline tables, layouts etc), so relying on static url + `module_name` is not an option anymore. Added module const `CATEGORY` which defines custom category in url (if present, otherwise defaults to `'component'`). That's probably the easiest way with the least amount of changes, but feel free to suggest different approach if needed.~~
3. As of now, `DonutChart.legend` nested view is basically outdated, as values for legend items are not available anymore, so neither special parametrized view, nor `_get_legend_item()` function are needed, but since the chart itself is a subject to change (numerous issues for donut chart are open), i'll leave that part as is for now, just in case values are returned in some upcoming PR.

### CODE REVIEW

**Comment by abalakh** [comment]
Some unrelated tests are failing on FF (donut test passes though). Not sure what's changed in FF or patternfly-react, will take a look tomorrow.

**Comment by abalakh** [comment]
Turns out it's an issue with patternfly-react, i've shared my findings in https://github.com/patternfly/patternfly-react/issues/1931#issuecomment-490066699 . @quarckster i think we should ignore this travis failure for now. Technically, we can workaround it by introducing `force_scroll=True` kwarg for all clicks in affected widgets, but imo it's gonna be too much ugly workarounds for issue which should be fixed soon.

**Comment by quarckster** [comment]
@abalakh PF4 documentation moved to https://www.patternfly.org/v4/documentation/react/components/aboutmodal and charts haven't been presented there yet.

**Comment by abalakh** [comment]
@quarckster mind if i take the task to update the repo to test against new docs (in case there is smth to work on, apart from url update 🙂 )? Or you're already looking into it?

**Comment by quarckster** [comment]
@abalakh Actually I've already changed the url in conftest.py, until charts are not presented in the new docs we could keep tests of donut charts skipped or override the url in a test fixture.

**Pull request merged**
